version: '3.7'

services:
  neloresys:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://neloresys:neloresys@db:5432/neloresys_dev
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=neloresys
      - POSTGRES_PASSWORD=neloresys
      - POSTGRES_DB=neloresys_dev

volumes:
  postgres_data:
